# 서버포트변경하기
# server.port
server: 
  port: 9091
  servlet: 
    encoding:
      charset: UTF-8
      force: true
# datasource설정하기
# spring.datasource.driver-class-name
spring:
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SPRING
    password: SPRING
    #jpa connection pool관리하기
    hikari: 
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: bspool
  jpa: 
    database: oracle 
    database-platform: org.hibernate.dialect.Oracle10gDialect 
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update 
      
# view화면 jsp로 활용하기
  mvc: 
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp
  # 업로드파일 크기 제한 설정하기
  servlet: 
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

    
  
# mybatis설정
#mybatis:
#  config-location: classpath:/config/mybatis-config.xml
#  mapper-locations: classpath:/mapper/**/*.xml



# 고정데이터 입력
# 기본경로, 기본포트, 계정관련내용
linux: 
  url: localhost:8989
  username: root
  base: /home/bsyoo      
 
       
# 로그에 대한 설정하기
logging:
  file: 
    name: logs/springboot.log     
  level:
    root: info
    '[com.bs.springboot]': info
      
      
      
  